---
title: "03 - APA Geodistance Calculator"
author: "Alec Stashevsky"
date: "June 27, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(openxlsx)
library(tidyverse)
library(data.table)
library(geosphere)
rm(list = ls()) # Clean R Environment
```


## Import Geo-unique Data
```{r Import}
path.in <- "C:/Users/alec.stashevsky/OneDrive - Cadmus/Documents/GAP Climate Research/GeoData/APA Geo-Unqiue Frequency Data.xlsx"

path.convention <- "C:/Users/alec.stashevsky/OneDrive - Cadmus/Documents/GAP Climate Research/GeoData/APA GeoData.xlsx"

nyc <- read_excel(path.in, sheet = "NYC 2018") %>% setDT()
sf <- read_excel(path.in, sheet = "SF 2019") %>% setDT()
phl <- read_excel(path.in, sheet = "PHL 2020") %>% setDT()
conventions <- read_xlsx(path.convention, sheet = "Convention Centers") %>%
  setDT()
```


## Calculate Geodistance to Convention Center
```{r Geodistance}
# Get convention center coordinates
nyc.dest <- as.numeric(conventions[STATE =="NY", c('lon', 'lat')])
sf.dest <- as.numeric(conventions[STATE =="CA", c('lon', 'lat')])
phl.dest <- as.numeric(conventions[STATE =="PA", c('lon', 'lat')])

# Calculate Geodistance in meters - with ellipsoidal method
nyc.gdist <- as.data.table(distGeo(nyc[, c('lon', 'lat')], nyc.dest))
sf.gdist <- as.data.table(distGeo(sf[, c('lon', 'lat')], sf.dest))
phl.gdist <- as.data.table(distGeo(phl[, c('lon', 'lat')], phl.dest))

# Merge onto Geo-unique data
final.nyc <- cbind(nyc, Meters = nyc.gdist)
final.sf <- cbind(sf, Meters = sf.gdist)
final.phl <- cbind(phl, Meters = phl.gdist)
```


## Descriptive Statistics
```{r Geodistance Stats}
# Summary Stats for unique location 
summary(final.nyc$Meters.V1)
summary(final.sf$Meters.V1)
summary(final.phl$Meters.V1)
# For some reason there is a single NA values in each set

# Summary Stats for total distances traveled
summary(final.nyc$Frequency * final.nyc$Meters.V1)
summary(final.sf$Frequency * final.sf$Meters.V1)
summary(final.phl$Frequency * final.phl$Meters.V1)

# Total distance traveled in kilometers
total.nyc <- sum(final.nyc$Frequency * final.nyc$Meters.V1, na.rm = TRUE)/1000
total.sf <- sum(final.sf$Frequency * final.sf$Meters.V1, na.rm = TRUE)/1000
total.phl <- sum(final.phl$Frequency * final.phl$Meters.V1, na.rm = TRUE)/1000
total.distance <- rbind(total.nyc, total.sf, total.phl)
```

```{r International / Domestic}
# Filter for domestic attendees
dom.nyc <- final.nyc[COUNTRY == "United States"]
dom.sf <- final.sf[COUNTRY == "United States"]
dom.phl <- final.phl[COUNTRY == "United States"]

# International attendees
intl.nyc <- final.nyc[COUNTRY != "United States"]
intl.sf <- final.sf[COUNTRY != "United States"]
intl.phl <- final.phl[COUNTRY != "United States"]

# Summary Counts (% Domestic - More in depth in Excel pivot tables)
nyc.dom.prop <- sum(dom.nyc$Frequency) / sum(final.nyc$Frequency)
sf.dom.prop <- sum(dom.sf$Frequency) / sum(final.sf$Frequency)
phl.dom.prop <- sum(dom.phl$Frequency) / sum(final.phl$Frequency)
dom.prop <- rbind(nyc.dom.prop, sf.dom.prop, phl.dom.prop)

# Summary Stats for total distances traveled
summary(dom.nyc$Frequency * dom.nyc$Meters.V1)
summary(dom.sf$Frequency * dom.sf$Meters.V1)
summary(dom.phl$Frequency * dom.phl$Meters.V1)
summary(intl.nyc$Frequency * intl.nyc$Meters.V1)
summary(intl.sf$Frequency * intl.sf$Meters.V1)
summary(intl.phl$Frequency * intl.phl$Meters.V1)

# Total distance traveled in kilometers
total.dom.nyc <- sum(dom.nyc$Frequency * dom.nyc$Meters.V1, na.rm = TRUE)/1000
total.dom.sf <- sum(dom.sf$Frequency * dom.sf$Meters.V1, na.rm = TRUE)/1000
total.dom.phl <- sum(dom.phl$Frequency * dom.phl$Meters.V1, na.rm = TRUE)/1000
total.domestic <- rbind(total.dom.nyc, total.dom.sf, total.dom.phl)

# Total distance traveled in kilometers
total.intl.nyc <- sum(intl.nyc$Frequency *
                        intl.nyc$Meters.V1, na.rm = TRUE)/1000
total.intl.sf <- sum(intl.sf$Frequency *
                       intl.sf$Meters.V1, na.rm = TRUE)/1000
total.intl.phl <- sum(intl.phl$Frequency *
                        intl.phl$Meters.V1, na.rm = TRUE)/1000
total.international <- rbind(total.intl.nyc, total.intl.sf, total.intl.phl)

# Combine distances into data.fame
table.names <- c("NYC 2018", "SF 2019", "PHL 2020")


total.table <- as.data.frame(cbind(table.names,
                                   total.domestic,
                                   total.international,
                                   total.distance,
                                   dom.prop))
# Fix headers
colnames(total.table) <- c("Meeting Location","Domestic (km)", "International (km)", "Total (km)", "% Domestic Attendance")
```


## Write Excel Copy
### Intended for subsequent analysis w/o R
```{r Write Geo-Unique Frequncy Data}
final.sets <- list("NYC 2018" = final.nyc,
                 "SF 2019" = final.sf,
                 "PHL 2020" = final.phl,
                 "Convention Centers" = conventions,
                 "Summary Statistics" = total.table)

write.xlsx(final.sets,
           file = "C:/Users/alec.stashevsky/OneDrive - Cadmus/Documents/GAP Climate Research/GeoData/APA Geodistance Data.xlsx")
```