---
title: "04 - Facility Location Simulation"
author: "Alec Stashevsky"
date: "July 3, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(openxlsx)
library(tidyverse)
library(data.table)
library(geosphere)
library(doBy)
rm(list = ls()) # Clean R Environment
```

## Import Geodistance Data from 03
```{r Import}
path.in <- "C:/Users/alec.stashevsky/OneDrive - Cadmus/Documents/GAP Climate Research/GeoData/APA Geodistance Data.xlsx"

nyc <- read_excel(path.in, sheet = "NYC 2018") %>% setDT()
sf <- read_excel(path.in, sheet = "SF 2019") %>% setDT()
phl <- read_excel(path.in, sheet = "PHL 2020") %>% setDT()
conventions <- read_xlsx(path.convention, sheet = "Convention Centers") %>%
  setDT()
```


Latitudes range from [-90, 90] and longitudes ranges from [-180, 180]. Here we create an algorithm to identify the optimal conference location based on the APA Annual Meetings geographic makeup of attendees.
```{r Geosample}
# Sample 10000 coordinates for initial whole-earth grid
coordinate.sample <- as.data.table(cbind(lon = round(runif(10000, -180, 180), 8),
                                         lat = round(runif(10000, -90, 90), 8)))

# Calculate geodesic distance for each coordinate
nyc.dist.log <- rep(NA, nrow(coordinate.sample))
for (i in 1:nrow(coordinate.sample)){
  nyc.dist.log[i] <- sum(distGeo(nyc[, c('lon', 'lat')],
                                 c(coordinate.sample$lon[i],
                                   coordinate.sample$lat[i])), na.rm = TRUE)
}

coordinate.sample[which.minn(nyc.dist.log, 10)]

grid <- rbind(c(min(coordinate.sample[which.minn(nyc.dist.log, 10)]$lon),
                min(coordinate.sample[which.minn(nyc.dist.log, 10)]$lat)),
              c(max(coordinate.sample[which.minn(nyc.dist.log, 10)]$lon),
                max(coordinate.sample[which.minn(nyc.dist.log, 10)]$lat)))



```

