---
title: "04 - Facility Location Algorithm"
author: "Alec Stashevsky"
date: "July 3, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits = 10) # need at least 8 decimal places for coordinates
library(readxl)
library(openxlsx)
library(tidyverse)
library(data.table)
library(geosphere)
library(doBy)
library(maps)
library(sp)
rm(list = ls()) # Clean R Environment
```

## Import Geodistance Data from 03
```{r Import}
path.in <- "C:/Users/alec.stashevsky/OneDrive - Cadmus/Documents/GAP Climate Research/GeoData/APA Geodistance Data.xlsx"

nyc <- read_excel(path.in, sheet = "NYC 2018") %>% setDT()
sf <- read_excel(path.in, sheet = "SF 2019") %>% setDT()
phl <- read_excel(path.in, sheet = "PHL 2020") %>% setDT()
conventions <- read_xlsx(path.convention, sheet = "Convention Centers") %>%
  setDT()
```


Latitudes range from [-90, 90] and longitudes ranges from [-180, 180]. Here we create an algorithm to identify the optimal conference location based on the APA Annual Meetings geographic makeup of attendees.
```{r Facility Location Algorithm}
# Sample 10000 coordinates for initial whole-earth grid
set.seed(32)
coordinate.sample <- as.data.table(cbind(lon = round(runif(100000, -180, 180), 8),
                                         lat = round(runif(100000, -90, 90), 8)))

# Calculate geodesic distance for each coordinate
## Again, we are using the WGS84 ellipsoidal distance
nyc.dist.log <- rep(NA, nrow(coordinate.sample))
for (i in 1:nrow(coordinate.sample)){
  nyc.dist.log[i] <- sum(distGeo(nyc[, c('lon', 'lat')],
                                 c(coordinate.sample$lon[i],
                                   coordinate.sample$lat[i])), na.rm = TRUE)
}

coordinate.rank <- arrange(cbind(coordinate.sample, nyc.dist.log), nyc.dist.log)
coordinate.rank <- cbind(coordinate.rank, rank = seq(1:nrow(coordinate.rank)))

# Create grid of confidence from 10 coordinates with the least geo-distance
grid <- as.matrix(rbind(
  c(min(coordinate.rank$lon[1:15]),
    min(coordinate.rank$lat[1:15])),
  c(max(coordinate.rank$lon[1:15]),
    max(coordinate.rank$lat[1:15]))))

# Find center point

# Plot 15 best sample coordinates to create region of confidence
map("state", col="grey20", fill=TRUE, bg="black", lwd=0.1,
    xlim = c(grid[1,1] - 2 , grid[2,1] + 3),
    ylim = c(grid[1,2] - 2, grid[2,2] + 3))

points(x = coordinate.rank$lon[1:15],
       y = coordinate.rank$lat[1:15],
       col = rgb(red = 255/255, green = 49/255, blue = 50/255, alpha = 1),
       pch = 10, cex = 2.8)

text(x = coordinate.rank$lon[1:15],
     y = coordinate.rank$lat[1:15],
     labels = coordinate.rank$rank[1:15],
     col = "white", cex = 0.8)

# Isolate maximum bounding polygon with best 15 approximations
target <- c(15, 11, 13, 10, 12, 9, 14)
poly.ordering <- as.matrix(rbind(
  coordinate.rank[target[1]],
  coordinate.rank[target[2]],
  coordinate.rank[target[3]],
  coordinate.rank[target[4]],
  coordinate.rank[target[5]],
  coordinate.rank[target[6]],
  coordinate.rank[target[7]]))


region <- makePoly(poly.ordering[,1:2], sp = TRUE)

polygon(poly.ordering, col = 
          rgb(red = 0, green = 1, blue = 1, alpha = 0.16))
```

